import bcrypt from 'bcryptjs'
import { Product } from './src/models/productModel'
import { User } from './src/models/userModel'
export const sampleProducts: Product[] = [
  {
    name: 'Birthday Cupcake',
    slug: 'birthday-cupcake',
    category: 'Baked Goods',
    image: '../images/birthday-cupcake.jpg',
    price: 7.68,
    countInStock: 3972,
    brand: 'Yummy in my tummy',
    rating: 4.28,
    numReviews: 6263,
    description:
      'A must have at any birthday party! Delicious, sweet and convenient cupcakes.',
    tags: [],
  },
  {
    name: 'Brownies',
    slug: 'brownies',
    category: 'Baked Goods',
    image: '../images/brownies.jpg',
    price: 7.68,
    countInStock: 3511,
    brand: 'Yummy in my tummy',
    rating: 3.03,
    numReviews: 7939,
    description:
      'Classic fudgey, chocolatey treat, best enjoyed with some ice cream!',
    tags: ['sale'],
  },
  {
    name: 'Candy Assorted',
    slug: 'candy-assorted',
    category: 'Candy',
    image: '../images/candy-assorted.jpg',
    price: 6.22,
    countInStock: 4968,
    brand: 'Yummy in my tummy',
    rating: 3.59,
    numReviews: 7765,
    description:
      'Professionally selected assortment of candies for you to enjoy.',
    tags: ['sale'],
  },
  {
    name: 'Candy Bites',
    slug: 'candy-bites',
    category: 'Candy',
    image: '../images/candy-bites.jpg',
    price: 3.01,
    countInStock: 4508,
    brand: 'Sweety Tooth Ltd.',
    rating: 1.88,
    numReviews: 2892,
    description: 'Small bites of candy.',
    tags: ['sale'],
  },
  {
    name: 'Carrot Cupcake',
    slug: 'carrot-cupcake',
    category: 'Baked Goods',
    image: '../images/carrot-cupcake.jpg',
    price: 6.34,
    countInStock: 4883,
    brand: 'Generic Candy Brand',
    rating: 3.86,
    numReviews: 3850,
    description: 'Classic holiday treat made with all-natural ingredients.',
    tags: [],
  },
  {
    name: 'Chocolate Balls',
    slug: 'chocolate-balls',
    category: 'Chocolate',
    image: '../images/chocolate-balls.jpg',
    price: 3.41,
    countInStock: 3779,
    brand: 'Generic Candy Brand',
    rating: 4.14,
    numReviews: 3438,
    description: 'Delicious small snacks, comes in a bag.',
    tags: ['gift'],
  },
  {
    name: 'Chocolate Chip Cookies',
    slug: 'chocolate-chip-cookies',
    category: 'Baked Goods',
    image: '../images/chocolate-chip-cookies.jpg',
    price: 3.5,
    countInStock: 4358,
    brand: 'Generic Candy Brand',
    rating: 0.68,
    numReviews: 1763,
    description:
      'Baked with love and care, our most popular cookies made with real chocolate chips.',
    tags: ['deal'],
  },
  {
    name: 'Chocolate Eggs',
    slug: 'chocolate-eggs',
    category: 'Chocolate',
    image: '../images/chocolate-eggs.jpg',
    price: 7.06,
    countInStock: 4804,
    brand: 'SCandy',
    rating: 0.19,
    numReviews: 5974,
    description:
      'Handmade chocolate eggs to be enjoyed at any time of the year.',
    tags: ['gift'],
  },
  {
    name: 'Chocolate Pops',
    slug: 'chocolate-pops',
    category: 'Chocolate',
    image: '../images/chocolate-pops.jpg',
    price: 6.64,
    countInStock: 4185,
    brand: 'Generic Candy Brand',
    rating: 0.9,
    numReviews: 7073,
    description:
      'Small pops of chocolate, ethically sourced and locally crafted.',
    tags: ['sale'],
  },
  {
    name: 'Cola',
    slug: 'cola',
    category: 'Soda',
    image: '../images/cola.jpg',
    price: 4.86,
    countInStock: 2945,
    brand: 'Sweetz & Things',
    rating: 3.38,
    numReviews: 2467,
    description: 'The ultimate thirst quencher, a classic cola.',
    tags: ['sale'],
  },
  {
    name: 'Cream Soda',
    slug: 'cream-soda',
    category: 'Soda',
    image: '../images/cream-soda.jpg',
    price: 3.05,
    countInStock: 3628,
    brand: 'SCandy',
    rating: 4.39,
    numReviews: 7211,
    description: 'Creamy and smooth, the perfect pairing for any sweet snack.',
    tags: ['sale'],
  },
  {
    name: 'Crystal Rock Candy',
    slug: 'crystal-rock-candy',
    category: 'Candy',
    image: '../images/crystal-rock-candy.jpg',
    price: 4.76,
    countInStock: 4631,
    brand: 'SCandy',
    rating: 4.95,
    numReviews: 8161,
    description:
      'Hard and very sweet, we are not responsible for chipped teeth.',
    tags: [],
  },
  {
    name: 'Cupcake',
    slug: 'cupcake',
    category: 'Baked Goods',
    image: '../images/cupcake.jpg',
    price: 2.67,
    countInStock: 3123,
    brand: 'Sweety Tooth Ltd.',
    rating: 3.11,
    numReviews: 6952,
    description: 'Order our special chocolate cupcakes here!',
    tags: ['gift'],
  },
  {
    name: 'Double Chocolate Cookie',
    slug: 'double-chocolate-cookie',
    category: 'Baked Goods',
    image: '../images/double-chocolate-cookie.jpg',
    price: 2.24,
    countInStock: 2076,
    brand: 'Generic Candy Brand',
    rating: 3.53,
    numReviews: 7352,
    description: 'Chocolate on the inside and chocolate on the outside!',
    tags: ['sale'],
  },
  {
    name: 'Fruit And Nut Bar',
    slug: 'fruit-and-nut-bar',
    category: 'Baked Goods',
    image: '../images/fruit-and-nut-bar.jpg',
    price: 1.85,
    countInStock: 2426,
    brand: 'Generic Candy Brand',
    rating: 3.63,
    numReviews: 2026,
    description: 'Delicious chocolate with a healthy fruit and nut filling.',
    tags: [],
  },
  {
    name: 'Gingerbread Cookies',
    slug: 'gingerbread-cookies',
    category: 'Baked Goods',
    image: '../images/gingerbread-cookies.jpg',
    price: 1.36,
    countInStock: 2415,
    brand: 'Generic Candy Brand',
    rating: 0.16,
    numReviews: 806,
    description:
      'Best enjoyed with a cup of hot chocolate alongside friends & family.',
    tags: ['gift'],
  },
  {
    name: 'Gummy Bears',
    slug: 'gummy-bears',
    category: 'Candy',
    image: '../images/gummy-bears.jpg',
    price: 2.54,
    countInStock: 2440,
    brand: 'Sweetz & Things',
    rating: 2.83,
    numReviews: 3053,
    description: 'Small bag of bear shaped, soft, gummy candies.',
    tags: [],
  },
  {
    name: 'Hard Fruit Candies',
    slug: 'hard-fruit-candies',
    category: 'Candy',
    image: '../images/hard-fruit-candies.jpg',
    price: 6.65,
    countInStock: 2931,
    brand: 'SCandy',
    rating: 3.46,
    numReviews: 9779,
    description:
      'Get your daily serving of fruits with these hard-shelled candies.',
    tags: [],
  },
  {
    name: 'Heart Candies',
    slug: 'heart-candies',
    category: 'Candy',
    image: '../images/heart-candies.jpg',
    price: 7.38,
    countInStock: 4320,
    brand: 'Sweetz & Things',
    rating: 4.8,
    numReviews: 1543,
    description:
      'What better way to let your loved-ones know you care than to give them a pack of these candies!',
    tags: [],
  },
  {
    name: 'Jelly Beans',
    slug: 'jelly-beans',
    category: 'Candy',
    image: '../images/jelly-beans.jpg',
    price: 6.14,
    countInStock: 4037,
    brand: 'Sweetz & Things',
    rating: 4.19,
    numReviews: 5437,
    description:
      'Every candy lover should keep a jar filled with these on their desk.',
    tags: [],
  },
  {
    name: 'Macaroons',
    slug: 'macaroons',
    category: 'Baked Goods',
    image: '../images/macaroons.jpg',
    price: 1.59,
    countInStock: 2906,
    brand: 'SCandy',
    rating: 1.88,
    numReviews: 755,
    description: 'A classic French coconut cookie.',
    tags: [],
  },
  {
    name: 'Milk Chocolate Bar',
    slug: 'milk-chocolate-bar',
    category: 'Chocolate',
    image: '../images/milk-chocolate-bar.jpg',
    price: 6.05,
    countInStock: 4319,
    brand: 'Yummy in my tummy',
    rating: 3.84,
    numReviews: 693,
    description:
      'The go to chocolate bar for many, a bar of delicious and ethically sourced milk chocolate.',
    tags: ['sale'],
  },
  {
    name: 'Mini Chocolate Bars',
    slug: 'mini-chocolate-bars',
    category: 'Chocolate',
    image: '../images/mini-chocolate-bars.jpg',
    price: 7.6,
    countInStock: 3101,
    brand: 'Sweety Tooth Ltd.',
    rating: 1.93,
    numReviews: 9367,
    description:
      'Get a pack of these mini chocolate bars and distribute them to your friends!',
    tags: ['sale', 'gift'],
  },
  {
    name: 'Nut Chocolate Bar',
    slug: 'nut-chocolate-bar',
    category: 'Chocolate',
    image: '../images/nut-chocolate-bar.jpg',
    price: 6.0,
    countInStock: 3943,
    brand: 'SCandy',
    rating: 1.7,
    numReviews: 7535,
    description: 'Warning, made with real peanuts and peanut butter.',
    tags: [],
  },
  {
    name: 'Orange Soda',
    slug: 'orange-soda',
    category: 'Soda',
    image: '../images/orange-soda.jpg',
    price: 1.44,
    countInStock: 3703,
    brand: 'Sweety Tooth Ltd.',
    rating: 3.19,
    numReviews: 8570,
    description:
      'Tangy and sweet orange soda, made with real orange flavoring.',
    tags: [],
  },
  {
    name: 'Sour Worms',
    slug: 'sour-worms',
    category: 'Candy',
    image: '../images/sour-worms.jpg',
    price: 5.01,
    countInStock: 2202,
    brand: 'Generic Candy Brand',
    rating: 0.12,
    numReviews: 2988,
    description:
      'Sour, soft and sweet, you will not find these hiding in an apple.',
    tags: ['deal', 'sale'],
  },
  {
    name: 'Swirl Lolly',
    slug: 'swirl-lolly',
    category: 'Candy',
    image: '../images/swirl-lolly.jpg',
    price: 4.22,
    countInStock: 2910,
    brand: 'Sweetz & Things',
    rating: 1.66,
    numReviews: 7313,
    description: 'A giant, swirly lollipop',
    tags: [],
  },
  {
    name: 'White Chocolate Macadamia Muffin',
    slug: 'white-chocolate-macadamia-muffin',
    category: 'Baked Goods',
    image: '../images/white-chocolate-macadamia-muffin.jpg',
    price: 4.1,
    countInStock: 3564,
    brand: 'Generic Candy Brand',
    rating: 2.93,
    numReviews: 528,
    description: 'Freshly baked with white chocolate and macadamia nuts.',
    tags: ['sale'],
  },
]

export const sampleUsers: User[] = [
  {
    name: 'John Doe',
    email: 'johndoe@example.com',
    password: bcrypt.hashSync('password'),
    isAdmin: false,
  },
  {
    name: 'Mr. Admin',
    email: 'admin@admin.com',
    password: bcrypt.hashSync('admin'),
    isAdmin: true,
  },
]
